### ISSUE TITLE
Restore from s3 endpoint fails to restore with "cli.restore_mysql() . ... not found"

### ISSUE THREAD

**Issue by ernstae** [twindb/backup#138]
Looks like a regression in behavior, where taking the output of `twindb-backup ls` s3 URLs results in a failed restore:

TwinDB-backup version: 2.15.10
Python version:  2.7.5
Kernel/OS:  3.10.0-862.2.3.el7.x86_64 / CentOS 7.3

```
root@**redactedhostname**:/tmp/mysql# twindb-backup --debug restore mysql s3://s3-bucket/**redactedhostname**/daily/mysql/mysql-2018-08-30_00_00_08.xbstream.gz
2018-09-06 02:17:09,295: DEBUG: cli.restore():177: restore: <ConfigParser.ConfigParser instance at 0x7f6707a865f0>
2018-09-06 02:17:09,296: DEBUG: cli.restore_mysql():189: mysql: <ConfigParser.ConfigParser instance at 0x7f6707a865f0>
2018-09-06 02:17:09,296: DEBUG: configuration.get_destination():29: Destination in the config s3
2018-09-06 02:17:10,977: ERROR: cli.restore_mysql():210: Copy **redactedhostname**/daily/mysql/mysql-2018-08-30_00_00_08.xbstream.gz not found

root@**redactedhostname**:/tmp/mysql# twindb-backup ls | grep s3://s3-bucket/**redactedhostname**/daily/mysql/mysql-2018-08-30_00_00_08.xbstream.gz
s3://s3-bucket/**redactedhostname**/daily/mysql/mysql-2018-08-30_00_00_08.xbstream.gz
```

Possibly related to #137 ?

Last known working 2.15.7

**Comment by akuzminsky** [comment]
That's a strange one. I couldn't reproduce it on 2.15.10. It also seems to be not related to #137.
From experience with S3 I can guess that maybe the copy wasn't visible at the moment of restore.
This is just a speculation though.
I noticed an occasional delay between when you upload a file to S3 and when it actually becomes visible to subsequent requests. 

Could you please run few more tests, preferably on 2.15.11 which I'm going to release tonight? If the problem repeats I'll have to put more effort in reproducing it.

**Comment by ernstae** [comment]
Not sure if this is a clue, but the stack trace looks like this:

```
Traceback (most recent call last):
  File "/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.15.10', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.10-py2.7.egg/twindb_backup/cli.py", line 280, in verify_mysql
    print(verify_mysql_backup(cfg, dst, backup_copy, hostname))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.10-py2.7.egg/twindb_backup/verify.py", line 40, in verify_mysql_backup
    copy = status[key]
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.10-py2.7.egg/twindb_backup/status/base_status.py", line 131, in __getitem__
    raise StatusKeyNotFound('Copy %s not found' % item)
twindb_backup.status.exceptions.StatusKeyNotFound: **redacted url of monthly or hourly full backup**
```

**Comment by ernstae** [comment]
Yes, you're correct, that the affected backups do not have corresponding entries in the `twindb-backup status` output.

I can, however, download the backup manually, and restore it.

Nothing in my logs suggest any errors running the original backups -- they're admittedly quite quiet.

A `backup daily` followed by a `mysql verify` and `status` of that backup reveals success.

I'm going to chalk this up to a transient error, possibly in an earlier version (or around the 2.15.8 release).  

Not sure if there's a potential feature request here -- but would be nice if there were maybe a `--force` option that allowed the fetch of the backup, and restore if it doesn't have a status entry?  I'm unsure how critical the status file is (I think it likely shows whether it's a full/incremental and where the LSN was at the time of the backup?)

**Comment by akuzminsky** [comment]
Status file is vitally important for incremental copies. To make one correctly you need to know LSN. To restore from one you need to know parent.
We are working on tightening the status durability. So far the status is being checksummed. But status write are not atomic yet.

Will think about the `--force` option. For full backups it totally makes sense. However for now the priority is reliable error detection and reporting and stable status updates.

**Comment by ernstae** [comment]
My issues seem only to focus around full backup copies.  All my incrementals have been working flawlessly.  Also, excited to see the binlog backup feature, too!  Thanks for all the work you do on this project.  I, for one, appreciate it!
