### ISSUE TITLE
List ssh client as dependency

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#15]
* TwinDB Backup version:
* Python version: 2.8.1
* Operating System: centos

### Description

Yes, some systems don't have `ssh` client. As long as `twindb-backup` depends on it, let's list it as a dependency.

### What I Did

```
# twindb-backup --debug ls
2017-01-14 18:43:23,388: INFO: ls.list_available_backups():11: Local copies:
2017-01-14 18:43:23,388: INFO: ls.list_available_backups():22: hourly copies:
2017-01-14 18:43:23,388: DEBUG: util.get_destination():14: Destination in the config ssh
2017-01-14 18:43:23,389: DEBUG: ssh.find_files():87: Running ssh -l root -o StrictHostKeyChecking=no -o PasswordAuthentication=no -p 22 -i /root/.ssh/id_rsa 127.0.0.1 find /tmp/backup/*/hourly -type f
Traceback (most recent call last):
  File "/usr/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.8.1', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.8.1-py2.7.egg/twindb_backup/cli.py", line 60, in ls
    list_available_backups(cfg)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.8.1-py2.7.egg/twindb_backup/ls.py", line 25, in list_available_backups
    for copy in dst.find_files(dst.remote_path, run_type):
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.8.1-py2.7.egg/twindb_backup/destination/ssh.py", line 88, in find_files
    proc = Popen(cmd, stdout=PIPE, stderr=PIPE)
  File "/opt/twindb-backup/embedded/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/opt/twindb-backup/embedded/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[root@9bf0f4a6a870 ~]# ssh
bash: ssh: command not found
```

**Comment by akuzminsky** [comment]
on CentOS 7:

```
# yum provides *bin/ssh
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.usc.edu
 * extras: mirrors.liquidweb.com
 * updates: mirrors.usc.edu
base/7/x86_64/filelists_db                                                                                                                                 | 6.6 MB  00:00:02
openssh-clients-6.6.1p1-31.el7.x86_64 : An open source SSH client applications
Repo        : base
Matched from:
Filename    : /usr/bin/ssh
```

**Comment by akuzminsky** [comment]
On CentOS 6:
```
# yum provides *bin/ssh
Loaded plugins: fastestmirror, ovl
base                                                                                                                                                       | 3.7 kB     00:00
base/primary_db                                                                                                                                            | 4.7 MB     00:03
extras                                                                                                                                                     | 3.4 kB     00:00
extras/primary_db                                                                                                                                          |  37 kB     00:00
updates                                                                                                                                                    | 3.4 kB     00:00
updates/primary_db                                                                                                                                         | 4.3 MB     00:01
base/filelists_db                                                                                                                                          | 6.4 MB     00:04
extras/filelists_db                                                                                                                                        |  38 kB     00:00
updates/filelists_db                                                                                                                                       | 2.9 MB     00:01
openssh-clients-5.3p1-117.el6.x86_64 : An open source SSH client applications
Repo        : base
Matched from:
Filename    : /usr/bin/ssh



openssh-clients-5.3p1-118.1.el6_8.x86_64 : An open source SSH client applications
Repo        : updates
Matched from:
Filename    : /usr/bin/ssh

```

**Comment by akuzminsky** [comment]
On debian jessie:
```
# apt-file search "/bin/ssh" | grep "ssh$"
openssh-client: /usr/bin/ssh
```

**Comment by akuzminsky** [comment]
Ubuntu trusty is also openssh-client:
```
# apt-file search "/bin/ssh" | grep "ssh$"
openssh-client: /usr/bin/ssh
```

**Comment by ovaistariq** [comment]
Fixed.
