### ISSUE TITLE
Deleting binlog issue

### ISSUE THREAD

**Issue by emper0r** [twindb/backup#193]
* TwinDB Backup version: 2.18.3 (fixed applied from issue #190) taking from PR. 
* Operating System: CentOS 7

### Description

Backup debug hourly

### What I Did

```
twindb-backup --debug backup hourly
```
output:

twindb-backup --debug backup hourly
2019-06-13 09:28:08,618: DEBUG: backup.run_backup_job():380: hourly
2019-06-13 09:28:11,963: DEBUG: backup.set_open_files_limit():304: Setting max files limit to 1048577
2019-06-13 09:28:12,331: DEBUG: mysql_status.candidate_parent():41: Looking a parent candidate for hourly run
2019-06-13 09:28:12,332: DEBUG: mysql_status.candidate_parent():47: Checking 0 hourly copies
2019-06-13 09:28:12,332: DEBUG: mysql_status.candidate_parent():47: Checking 0 daily copies
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():47: Checking 0 weekly copies
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():47: Checking 0 monthly copies
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():47: Checking 0 yearly copies
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():56: No eligible parents
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():41: Looking a parent candidate for hourly run
2019-06-13 09:28:12,333: DEBUG: mysql_status.candidate_parent():47: Checking 0 hourly copies
2019-06-13 09:28:12,334: DEBUG: mysql_status.candidate_parent():47: Checking 0 daily copies
2019-06-13 09:28:12,334: DEBUG: mysql_status.candidate_parent():47: Checking 0 weekly copies
2019-06-13 09:28:12,334: DEBUG: mysql_status.candidate_parent():47: Checking 0 monthly copies
2019-06-13 09:28:12,334: DEBUG: mysql_status.candidate_parent():47: Checking 0 yearly copies
2019-06-13 09:28:12,334: DEBUG: mysql_status.candidate_parent():56: No eligible parents
2019-06-13 09:28:12,334: DEBUG: backup.backup_mysql():146: Creating source {'backup_type': 'full', 'dst': <twindb_backup.destination.ssh.Ssh object at 0x7f41bac20e90>, 'xtrabackup_binary': '/opt/twindb-backup/embedded/bin/xtrabackup'}
2019-06-13 09:28:12,335: DEBUG: base_source._get_name():63: Suffix = xbstream.gz
2019-06-13 09:28:12,336: DEBUG: base_source._get_name():63: Suffix = xbstream.gz
2019-06-13 09:28:12,336: DEBUG: ssh.execute_command():136: Executing: mkdir -p "/mysql/backup/sql-server/hourly/mysql"
2019-06-13 09:28:12,437: DEBUG: client.execute():110: Executing command: mkdir -p "/mysql/backup/sql-server/hourly/mysql"
2019-06-13 09:28:12,697: DEBUG: client.get_remote_handlers():165: Try to get remote handlers: cat - > /mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz
2019-06-13 09:28:12,908: DEBUG: mysql_source.is_galera():466: Galera is not supported or not enabled
2019-06-13 09:28:12,909: DEBUG: mysql_source.get_stream():193: Running /opt/twindb-backup/embedded/bin/xtrabackup --defaults-file=/etc/twindb/my.cnf --stream=xbstream --host=127.0.0.1 --backup --target-dir .
2019-06-13 09:28:12,910: DEBUG: mysql_source.is_galera():466: Galera is not supported or not enabled
2019-06-13 09:28:12,911: DEBUG: mysql_source.get_stream():199: Running /opt/twindb-backup/embedded/bin/xtrabackup --defaults-file=/etc/twindb/my.cnf --stream=xbstream --host=127.0.0.1 --backup --target-dir .
2019-06-13 09:28:12,915: DEBUG: base.get_stream():41: Running gzip -9 -c -
2019-06-13 09:28:12,925: DEBUG: base.get_stream():41: Running tee /mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz
2019-06-13 09:42:53,832: DEBUG: mysql_source.get_stream():220: Successfully streamed xtrabackup output
2019-06-13 09:42:53,832: DEBUG: mysql_source._update_backup_info():241: xtrabackup error log file /tmp/tmpEAr3hJ
2019-06-13 09:42:53,932: DEBUG: base_source._get_name():63: Suffix = xbstream.gz
2019-06-13 09:42:53,932: DEBUG: backup.backup_mysql():158: Backup copy name: sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz
2019-06-13 09:42:54,201: DEBUG: client.execute():110: Executing command: bash -c 'if test -d /mysql/backup/sql-server/hourly/mysql ; then find /mysql/backup/sql-server/hourly/mysql -maxdepth 1 -type f; fi'
2019-06-13 09:42:54,336: DEBUG: client.list_files():197: COUT:
/mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz

2019-06-13 09:42:54,336: DEBUG: client.list_files():198: CERR:
/usr/bin/id: cannot find name for group ID 948600513

2019-06-13 09:42:54,336: DEBUG: base_destination._match_files():137: Pattern: None
2019-06-13 09:42:54,337: DEBUG: base_destination._match_files():138: Unfiltered files: ['/mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz']
2019-06-13 09:42:54,338: DEBUG: base_destination._match_files():146: Filtered files: ['/mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz']
2019-06-13 09:42:54,338: DEBUG: mysql_source.apply_retention_policy():283: Remote copies: ['/mysql/backup/sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz']
2019-06-13 09:42:54,338: DEBUG: __init__.get_files_to_delete():116: Retain 24 files
2019-06-13 09:42:54,339: DEBUG: __init__.delete_local_files():134: Local copies: ['/mysql/backup//sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz']
2019-06-13 09:42:54,339: DEBUG: __init__.get_files_to_delete():116: Retain 1 files
2019-06-13 09:42:54,339: DEBUG: backup.backup_mysql():181: status after apply_retention_policy():
{"monthly": {}, "hourly": {"sql-server/hourly/mysql/mysql-2019-06-13_09_28_12.xbstream.gz": {"galera": false, "binlog": "binlog_node1.000126", "run_type": "hourly", "name": "mysql-2019-06-13_09_28_12.xbstream.gz", "parent": null, "lsn": 112324075203, "type": "full", "backup_finished": 1560411773, "wsrep_provider_version": null, "host": "sql-server", "backup_started": 1560410891, "position": 26331384, "config": [{"/etc/my.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/mysqld_safe.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/replica.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/custom.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/mysqld.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/binlog.cnf": "ciphertext"}, {"/etc/percona-server.conf.d/network.cnf": "ciphertext"}]}}, "yearly": {}, "daily": {}, "weekly": {}}
2019-06-13 09:42:54,546: DEBUG: backup.backup_mysql():193: Callbacks are [(<twindb_backup.modifiers.keeplocal.KeepLocal object at 0x7f41ba17fad0>, {'dst': <twindb_backup.destination.ssh.Ssh object at 0x7f41bac20e90>, 'keep_local_path': '/mysql/backup/'})]
2019-06-13 09:42:54,978: DEBUG: backup.backup_binlogs():217: Latest copied binlog None
2019-06-13 09:42:55,004: DEBUG: ssh.execute_command():136: Executing: mkdir -p "/mysql/backup/sql-server/binlog"
2019-06-13 09:42:55,102: DEBUG: client.execute():110: Executing command: mkdir -p "/mysql/backup/sql-server/binlog"
2019-06-13 09:42:55,292: DEBUG: client.get_remote_handlers():165: Try to get remote handlers: cat - > /mysql/backup/sql-server/binlog/binlog_node1.000126.gz
2019-06-13 09:42:55,368: DEBUG: binlog_source.get_stream():157: Running cat /mysql/binlogs/binlog_node1.000126
2019-06-13 09:42:55,373: DEBUG: base.get_stream():41: Running gzip -9 -c -
2019-06-13 09:42:55,380: DEBUG: base.get_stream():41: Running tee /mysql/backup/sql-server/binlog/binlog_node1.000126.gz
2019-06-13 09:42:59,218: DEBUG: binlog_source.get_stream():168: Successfully streamed /mysql/binlogs/binlog_node1.000126
2019-06-13 09:42:59,333: DEBUG: backup.backup_binlogs():254: Reviewing copy BinlogCopy: file name: binlog_node1.000126, created at: 1559056971. Now: 1560411779
2019-06-13 09:42:59,333: DEBUG: backup.backup_binlogs():259: Deleting copy that was taken 1354808 seconds ago
2019-06-13 09:42:59,334: DEBUG: ssh.execute_command():136: Executing: rm sql-server/binlog/binlog_node1.000126.gz
2019-06-13 09:42:59,468: DEBUG: client.execute():110: Executing command: rm sql-server/binlog/binlog_node1.000126.gz
2019-06-13 09:42:59,561: ERROR: client.execute():132: Failed to execute command rm sql-server/binlog/binlog_node1.000126.gz
2019-06-13 09:42:59,561: ERROR: client.execute():133: /usr/bin/id: cannot find name for group ID 948600513
**rm: cannot remove ‘sql-server/binlog/binlog_node1.000126.gz’: No such file or directory**

Traceback (most recent call last):
  File "/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.18.2', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/cli.py", line 128, in backup
    binlogs_only=binlogs_only
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/backup.py", line 385, in run_backup_job
    binlogs_only=binlogs_only
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/backup.py", line 325, in backup_everything
    backup_binlogs(run_type, twindb_config)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/backup.py", line 261, in backup_binlogs
    dst.delete(copy.key + ".gz")
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/destination/ssh.py", line 94, in delete
    self.execute_command(cmd)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/destination/ssh.py", line 141, in execute_command
    background=background
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup/ssh/client.py", line 136, in execute
    % (cmd, exit_code)
twindb_backup.ssh.exceptions.SshClientException: rm sql-server/binlog/binlog_node1.000126.gz exited with code 1

**Local backup repository on sql-server:**

/mysql/backup/sql-server:
total 12K
drwxr-xr-x 2 root root   36 Jun 13 09:42 binlog
drwxr-xr-x 3 root root   19 Jun 13 09:28 hourly
-rw-r--r-- 1 root root 8.3K Jun 13 09:42 status

/mysql/backup/sql-server/binlog:
total 4.5M
-rw-r--r-- 1 root root 4.5M Jun 13 09:42 binlog_node1.000126.gz

/mysql/backup/sql-server/hourly:
total 0
drwxr-xr-x 2 root root 51 Jun 13 09:28 mysql

/mysql/backup/sql-server/hourly/mysql:
total 826M
-rw-r--r-- 1 root root 826M Jun 13 09:42 mysql-2019-06-13_09_28_12.xbstream.gz
[root@sql-server ~]# ls -lhR /mysql/backup/sql-server/
[root@sql-server ~]# ls -lhR /mysql/backup/sql-server/
/mysql/backup/sql-server/:
total 12K
drwxr-xr-x 2 root root   36 Jun 13 09:42 binlog
drwxr-xr-x 3 root root   19 Jun 13 09:28 hourly
-rw-r--r-- 1 root root 8.3K Jun 13 09:42 status

**/mysql/backup/sql-server/binlog:
total 4.5M
-rw-r--r-- 1 root root 4.5M Jun 13 09:42 binlog_node1.000126.gz**

/mysql/backup/sql-server/hourly:
total 0
drwxr-xr-x 2 root root 51 Jun 13 09:28 mysql

/mysql/backup/sql-server/hourly/mysql:
total 826M
-rw-r--r-- 1 root root 826M Jun 13 09:42 mysql-2019-06-13_09_28_12.xbstream.gz

**remote repository:**

ls -lhR /mysql/backup/sql-server/
/mysql/backup/sql-server/:
total 12K
drwxr-xr-x 2 user backup   36 Jun 13 09:42 binlog
drwxr-xr-x 3 user backup   19 Jun 13 09:28 hourly
-rw-r--r-- 1 user backup 8.3K Jun 13 09:42 status

**/mysql/backup/sql-server/binlog:
total 4.5M
-rw-r--r-- 1 user backup 4.5M Jun 13 09:42 binlog_node1.000126.gz**

/mysql/backup/sql-server/hourly:
total 0
drwxr-xr-x 2 user backup 51 Jun 13 09:28 mysql

/mysql/backup/sql-server/hourly/mysql:
total 826M
-rw-r--r-- 1 user backup 826M Jun 13 09:42 mysql-2019-06-13_09_28_12.xbstream.gz

**Comment by akuzminsky** [comment]
Fixed in 2.20.1
