### ISSUE TITLE
script doesn't create a host directory

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#32]
* TwinDB Backup version: 2.9.3

### Description

When storing a local copy `twindb-backup` should create directory for a host it takes backup from.

Let's say `keep_local_copy=/var/log/mysql/backup`, hostname is `ip-10-10-10-10`.
If `/var/log/mysql/backup/ip-10-10-10-10` doesn't exist the script will crash with traceback:
```
Traceback (most recent call last):
File "/usr/bin/twindb-backup", line 9, in <module>
load_entry_point('twindb-backup==2.9.3', 'console_scripts', 'twindb-backup')()
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in _call_
return self.main(*args, **kwargs)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
return ctx.invoke(f, obj, *args[1:], **kwargs)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.9.3-py2.7.egg/twindb_backup/cli.py", line 53, in backup
run_backup_job(cfg, run_type)
File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.9.3-py2.7.egg/twindb_backup/backup.py", line 140, in run_backup_job
raise err
IOError: [Errno 2] No such file or directory: '/var/log/mysql/backup//ip-10-10-10-10/status'
```

**Comment by mkryva** [comment]
Can't reproduce. May be, this bug have fixed earlier
