### ISSUE TITLE
make package now fails due to OpenSSL validation issues

### ISSUE THREAD

**Issue by ernstae** [twindb/backup#322]
### Description
Building the package is no longer working.  This is a challenge as we were trying to build support for Azure blob storage and could use some help fixing this.

### What I Did
* Download source
* `make package`

```
Fetching ruby-progressbar 1.11.0
Installing ruby-progressbar 1.11.0
Fetching omnibus 8.0.9
Installing omnibus 8.0.9
Using omnibus-software 4.0.0 from https://github.com/twindb/omnibus-software.git (at master@782235f)
Bundle complete! 5 Gemfile dependencies, 108 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from minitar:
The `minitar` executable is no longer bundled with `minitar`. If you are
expecting this executable, make sure you also install `minitar-cli`.
+ bin/omnibus build twindb-backup
                    [CLI] I | 2022-01-07T22:06:07+00:00 | Using config from 'omnibus.rb'
Building twindb-backup 2.20.2...
 [Software: config_guess] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for config_guess
  [Software: preparation] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for preparation
[NullFetcher: preparation] I | 2022-01-07T22:06:07+00:00 | Fetching `preparation' (nothing to fetch)
       [Software: libffi] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for libffi
      [Software: libyaml] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for libyaml
     [NetFetcher: libffi] I | 2022-01-07T22:06:07+00:00 | Downloading from `https://www.mirrorservice.org/sites/sourceware.org/pub/libffi/libffi-3.3.tar.gz'
      [Software: ncurses] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for ncurses
      [Software: libedit] I | 2022-01-07T22:06:07+00:00 | Resolving manifest entry for libedit
    [NetFetcher: libedit] I | 2022-01-07T22:06:07+00:00 | Downloading from `http://www.thrysoee.dk/editline/libedit-20120601-3.0.tar.gz'
    [NetFetcher: ncurses] I | 2022-01-07T22:06:07+00:00 | Downloading from `https://s3.amazonaws.com/twindb-release/ncurses-5.9.tar.gz'
    [NetFetcher: libyaml] I | 2022-01-07T22:06:07+00:00 | Downloading from `https://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz'


Progress: |
Progress: |Progress: |
Progress: |#<Thread:0x0000000002140e90@/usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:55 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:35:in `open'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/download_helpers.rb:81:in `download_file!'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/fetchers/net_fetcher.rb:176:in `download'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/software.rb:903:in `fetch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:62:in `block (4 levels) in initialize'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:60:in `loop'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:60:in `block (3 levels) in initialize'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:59:in `catch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:59:in `block (2 levels) in initialize'
/usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	from /usr/local/rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/open-uri.rb:35:in `open'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/download_helpers.rb:81:in `download_file!'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/fetchers/net_fetcher.rb:176:in `download'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/software.rb:903:in `fetch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/project.rb:1067:in `block (3 levels) in download'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:62:in `block (4 levels) in initialize'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:60:in `loop'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:60:in `block (3 levels) in initialize'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:59:in `catch'
	from /usr/local/rvm/gems/ruby-2.6.1/gems/omnibus-8.0.9/lib/omnibus/thread_pool.rb:59:in `block (2 levels) in initialize'
make: *** [Makefile:213: package] Error 1
```

**Comment by akuzminsky** [comment]
I saw this issue on older Ubuntu versions. The reason for that is expired CA in a docker image that `make package` starts.
I fixed this problem for focal, bionic (CentOS 7 seems fine). Older Ubuntu versions will probably be deprecated because it becomes too difficult to cope with dependencies on them.
I wonder what OS do you use?

**Comment by akuzminsky** [comment]
Foxed in https://github.com/twindb/backup/releases/tag/3.0.0
