### ISSUE TITLE
twindb-backup clone mysql fails to determine free memory

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#54]
* TwinDB Backup version: 2.14.1

### Description
```
$ twindb-backup --config ~/.twindb-backup.cfg clone mysql a.b.c.d e.f.g.h
2017-10-13 13:23:25,730: ERROR: clone.clone_mysql():85: Failed to stop MySQL on <twindb_backup.destination.ssh.Ssh object at 0x7f87b599dcd0>
Traceback (most recent call last):
  File "/home/okuzminskyi/.virtualenvs/backup/bin/twindb-backup", line 11, in <module>
    load_entry_point('twindb-backup', 'console_scripts', 'twindb-backup')()
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/okuzminskyi/.virtualenvs/backup/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/okuzminskyi/src/backup/twindb_backup/cli.py", line 231, in clone_mysql_backup
    netcat_port=netcat_port)
  File "/home/okuzminskyi/src/backup/twindb_backup/clone.py", line 130, in clone_mysql
    binlog, position = dst_mysql.apply_backup(datadir)
  File "/home/okuzminskyi/src/backup/twindb_backup/source/remote_mysql_source.py", line 166, in apply_backup
    free_mem = int(stdout_.read()) * 1024
ValueError: invalid literal for int() with base 10: ''
```

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/56
