### ISSUE TITLE
OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by fonthead** [twindb/backup#65]
Python: 2.7.12

I am now getting this error on one server running 2.14.1

```
Traceback (most recent call last):
 File "/usr/bin/twindb-backup", line 9, in <module>
   load_entry_point('twindb-backup==2.14.1', 'console_scripts', 'twindb-backup')()
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
   return ctx.invoke(f, obj, *args[1:], **kwargs)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/cli.py", line 72, in backup
   run_backup_job(cfg, run_type)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/backup.py", line 254, in run_backup_job
   backup_everything(run_type, cfg)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/backup.py", line 207, in backup_everything
   backup_mysql(run_type, config)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/backup.py", line 148, in backup_mysql
   dst.status(status)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/destination/base_destination.py", line 122, in status
   return self._write_status(status)
 File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.14.1-py2.7.egg/twindb_backup/destination/ssh.py", line 137, in _write_status
   proc = Popen(cmd)
 File "/opt/twindb-backup/embedded/lib/python2.7/subprocess.py", line 710, in __init__
   errread, errwrite)
 File "/opt/twindb-backup/embedded/lib/python2.7/subprocess.py", line 1335, in _execute_child
   raise child_exception
OSError: [Errno 7] Argument list too long
```

**Comment by mkryva** [comment]
Hi. May You write your input args ?

**Comment by akuzminsky** [comment]
@fonthead would you mind sharing your `twindb-backup.cfg`?

**Comment by fonthead** [comment]
Sure, find it attached. Thanks for looking!


Ethan Dunham, President
Fonthead Design Inc.
———————————————————————
w: www.fonthead.com
p: 302.479.7922
———————————————————————

**Comment by akuzminsky** [comment]
@fonthead I'm sorry, it looks like github strips out attachments. Could you please paste it in comments or send me to aleks@twindb.com ?
