### ISSUE TITLE
malformed logging

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#75]
* TwinDB Backup version: 2.14.4

### Description

clone doesn't log properly

```
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/opt/rh/python27/root/usr/lib64/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file clone.py, line 126
```

**Comment by mkryva** [comment]
It was fixed in next commits.
