### ISSUE TITLE
corrupted status file

### ISSUE THREAD

**Issue by akuzminsky** [twindb/backup#87]
* TwinDB Backup version: 1.5.3

### Description

malformed status file causes the tool crash

### What I Did

```
2018-01-23 16:44:11,617: DEBUG: backup.run_backup_job():233: daily
2018-01-23 16:44:12,473: DEBUG: backup.set_open_files_limit():169: Setting max files limit to 1048577
2018-01-23 16:44:12,474: DEBUG: __init__.get_directories_to_backup():118: Not backing up files
2018-01-23 16:44:12,474: DEBUG: configuration.get_destination():28: Destination in the config ssh
2018-01-23 16:44:12,475: DEBUG: base_source._get_name():50: Suffix = xbstream
2018-01-23 16:44:12,476: DEBUG: ssh.execute_command():266: Executing: mkdir -p "/backups_mysql/www.xxx.com/daily/mysql"
2018-01-23 16:44:12,873: DEBUG: client.execute():72: Executing mkdir -p "/backups_mysql/www.xxx.com/daily/mysql"
2018-01-23 16:44:13,350: DEBUG: mysql_source.get_stream():123: Running innobackupex --defaults-file=/etc/twindb/my.cnf --stream=xbstream --host=127.0.0.1 .
2018-01-23 16:44:13,355: DEBUG: mysql_source.get_stream():129: Running innobackupex --defaults-file=/etc/twindb/my.cnf --stream=xbstream --host=127.0.0.1 .
2018-01-23 18:02:23,974: DEBUG: mysql_source.get_stream():143: Successfully streamed innobackupex output
2018-01-23 18:02:23,975: DEBUG: mysql_source._update_backup_info():163: innobackupex error log file /tmp/tmpCi7ULD
2018-01-23 18:02:24,271: DEBUG: client.execute():72: Executing bash -c 'if test -s /backups_mysql/www.xxx.com/status; then echo exists; else echo not_exists; fi'
Traceback (most recent call last):
  File "/usr/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.15.3', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/cli.py", line 82, in backup
    run_backup_job(cfg, run_type, lock_file=lock_file)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/backup.py", line 235, in run_backup_job
    backup_everything(run_type, cfg)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/backup.py", line 186, in backup_everything
    backup_mysql(run_type, config)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/backup.py", line 119, in backup_mysql
    status = prepare_status(dst, src, run_type, src_name, backup_start)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/backup.py", line 136, in prepare_status
    status = dst.status()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/destination/base_destination.py", line 120, in status
    return self._read_status()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/destination/ssh.py", line 230, in _read_status
    return json.loads(base64.b64decode(stdout.read()))
  File "/opt/twindb-backup/embedded/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/twindb-backup/embedded/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/twindb-backup/embedded/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 170178 (char 170177)


```

**Comment by akuzminsky** [comment]
possibly related
```
[root@dev mariadb]# twindb-backup status
Traceback (most recent call last):
  File "/usr/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.15.3', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in _call_
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, args[1:]
, *kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/cli.py", line 128, in status
    print(json.dumps(dst.status(), indent=4, sort_keys=True))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/destination/base_destination.py", line 120, in status
    return self._read_status()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/destination/ssh.py", line 230, in _read_status
    return json.loads(base64.b64decode(stdout.read()))
  File "/opt/twindb-backup/embedded/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/opt/twindb-backup/embedded/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/twindb-backup/embedded/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 48220 (char 48219)
```

**Comment by akuzminsky** [comment]
and restore fails due to a status
```
2018-01-25 23:03:57,459: WARNING: restore._get_status_key():39: key dev.xxx.com/hourly/mysql/mysql-2018-01-25_22_20_49.xbstream.gz is not found
Traceback (most recent call last):
  File "/usr/bin/twindb-backup", line 9, in <module>
    load_entry_point('twindb-backup==2.15.3', 'console_scripts', 'twindb-backup')()
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in _call_
    return self.main(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, args[1:]
, *kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/cli.py", line 160, in restore_mysql
    restore_from_mysql(cfg, backup_copy, dst)
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/restore.py", line 352, in restore_from_mysql
    if get_backup_type(status, key) == "full":
  File "/opt/twindb-backup/embedded/lib/python2.7/site-packages/twindb_backup-2.15.3-py2.7.egg/twindb_backup/restore.py", line 72, in get_backup_type
    raise DestinationError('Unknown backup type for backup copy %s' % key)
twindb_backup.destination.exceptions.DestinationError: Unknown backup type for backup copy dev.xxx.com/hourly/mysql/mysql-2018-01-25_22_20_49.xbstream.gz
```

**Comment by mkryva** [comment]
https://github.com/twindb/backup/pull/89
